export type Lang = 'en' | 'ko'
export type T = { en: string; ko: string }
export const t = (obj: T, lang: Lang) => obj[lang]

export const NAV = {
  logo:     { en: 'Shinhara',    ko: '신하라' },
  services: { en: 'Services',  ko: '서비스' },
  about:    { en: 'About',     ko: '소개' },
  gallery:  { en: 'Gallery',   ko: '갤러리' },
  contact:  { en: 'Contact',   ko: '연락처' },
  book:     { en: 'Book Now',  ko: '예약하기' },
}

export const SERVICES = [
  {
    slug: 'nail-art',
    accent: '#f0c4d4',
    accentStrong: '#e879a0',
    chip: 'chip-pink',
    name:    { en: 'Nail Art & Design',      ko: '네일 아트 & 디자인' },
    short:   { en: 'Nail Art',               ko: '네일 아트' },
    tagline: { en: 'Your nails, your story', ko: '네일로 표현하는 나의 이야기' },
    desc:    { en: 'From minimalist neutrals to intricate 3D florals — expert artistry tailored to your vision, every single time.', ko: '미니멀한 누드부터 정교한 3D 플로럴까지 — 당신의 비전에 맞춘 전문적인 아티스트리.' },
    duration:{ en: '45 – 90 min', ko: '45–90분' },
    from:    { en: 'From $45',    ko: '$45부터' },
    tags:    { en: ['Gel', 'Acrylic', '3D Art', 'Extensions', 'Chrome', 'Nail Repair'], ko: ['젤', '아크릴', '3D 아트', '연장', '크롬', '네일 보수'] },
    steps: [
      { en: 'Shape consultation & design selection', ko: '모양 상담 및 디자인 선택' },
      { en: 'Nail prep, filing & buffing', ko: '네일 준비, 파일링 및 버핑' },
      { en: 'Base coat & colour application', ko: '베이스 코트 및 컬러 도포' },
      { en: 'Art work, gems, or chrome finish', ko: '아트 작업, 젬 또는 크롬 마감' },
      { en: 'Top coat seal & aftercare guidance', ko: '탑 코트 마감 및 사후 관리 안내' },
    ],
    faq: [
      { q: { en: 'How long do gel nails last?', ko: '젤 네일은 얼마나 지속되나요?' }, a: { en: 'Gel nails typically last 2–3 weeks with proper care. We recommend moisturising cuticles daily.', ko: '젤 네일은 적절한 관리 시 보통 2~3주 지속됩니다. 매일 큐티클 보습을 권장합니다.' } },
      { q: { en: 'Can I bring my own nail design?', ko: '직접 디자인을 가져올 수 있나요?' }, a: { en: 'Absolutely — bring inspo photos and our artists will recreate or adapt the design for you.', ko: '물론입니다 — 영감 사진을 가져오시면 아티스트가 디자인을 재현하거나 응용해 드립니다.' } },
      { q: { en: 'Do you offer nail repairs between appointments?', ko: '예약 사이에 네일 보수가 가능한가요?' }, a: { en: 'Yes — we offer a quick repair service for single nails, typically 10–15 minutes.', ko: '네 — 단일 네일 보수 서비스를 제공하며, 보통 10~15분 소요됩니다.' } },
    ],
    packages: [
      { name: { en: 'Essential', ko: '에센셜' }, price: '$45', period: { en: 'per session', ko: '회당' }, features: { en: ['Classic gel colour', 'Basic nail art', 'Standard filing & shape', 'Cuticle care'], ko: ['클래식 젤 컬러', '기본 네일 아트', '표준 파일링 & 모양', '큐티클 케어'] } },
      { name: { en: 'Signature', ko: '시그니처' }, price: '$75', period: { en: 'per session', ko: '회당' }, featured: true, features: { en: ['Premium gel or acrylic', 'Custom nail art design', 'Shape consultation', '3D elements or chrome', 'Aftercare kit'], ko: ['프리미엄 젤 또는 아크릴', '커스텀 네일 아트', '모양 상담', '3D 요소 또는 크롬', '애프터케어 키트'] } },
      { name: { en: 'Monthly Club', ko: '월간 클럽' }, price: '$59', period: { en: '/ month', ko: '/ 월' }, badge: { en: 'SAVE 20%', ko: '20% 절약' }, features: { en: ['1 Signature session / month', 'Priority booking', 'Free single repairs', '10% off retail products'], ko: ['월 시그니처 세션 1회', '우선 예약', '단일 네일 무료 보수', '리테일 제품 10% 할인'] } },
    ],
    products: [
      { name: 'OPI GelColor Top Coat', price: '$22', tag: { en: 'Staff Favourite', ko: '스태프 추천' }, color: '#f0c4d4' },
      { name: 'CND SolarOil Nail & Cuticle Care', price: '$14', tag: { en: 'Bestseller', ko: '베스트셀러' }, color: '#bbf7d0' },
      { name: 'Essie Gel Couture Base Coat', price: '$18', tag: { en: 'New In', ko: '신제품' }, color: '#bae6fd' },
    ],
  },
  {
    slug: 'facials',
    accent: '#c4b5fd',
    accentStrong: '#7c3aed',
    chip: 'chip-purple',
    name:    { en: 'Luxury Facials',          ko: '럭셔리 페이셜' },
    short:   { en: 'Facials',                 ko: '페이셜' },
    tagline: { en: 'Science meets serenity',  ko: '과학과 평온이 만나는 곳' },
    desc:    { en: 'Science-backed, skin-transforming treatments tailored to your unique complexion. Walk in stressed, walk out glowing.', ko: '과학적 근거 기반의 피부 변환 트리트먼트. 스트레스를 안고 들어와 빛나며 나가세요.' },
    duration:{ en: '60 – 90 min', ko: '60–90분' },
    from:    { en: 'From $85',    ko: '$85부터' },
    tags:    { en: ['Deep Cleanse', 'HydraFacial', 'LED Therapy', 'Chemical Peel', 'Microdermabrasion'], ko: ['딥 클렌징', '하이드라페이셜', 'LED 테라피', '케미컬 필', '미세박피술'] },
    steps: [
      { en: 'Skin analysis & consultation', ko: '피부 분석 및 상담' },
      { en: 'Deep cleanse & steam', ko: '딥 클렌징 및 스팀' },
      { en: 'Exfoliation treatment', ko: '각질 제거 트리트먼트' },
      { en: 'Custom serum & mask', ko: '커스텀 세럼 및 마스크' },
      { en: 'LED therapy & SPF finish', ko: 'LED 테라피 및 SPF 마무리' },
    ],
    faq: [
      { q: { en: 'How often should I get a facial?', ko: '페이셜은 얼마나 자주 받아야 하나요?' }, a: { en: 'For most skin types, every 4–6 weeks is ideal to align with your skin\'s natural renewal cycle.', ko: '대부분의 피부 타입에는 피부의 자연 갱신 주기에 맞춰 4~6주마다 받는 것이 이상적입니다.' } },
      { q: { en: 'What should I avoid before a facial?', ko: '페이셜 전에 무엇을 피해야 하나요?' }, a: { en: 'Avoid retinoids and exfoliants 48h before, and arrive with a clean face if possible.', ko: '48시간 전에 레티노이드와 각질 제거제를 피하고, 가능하면 깨끗한 얼굴로 오세요.' } },
    ],
    packages: [
      { name: { en: 'Refresh', ko: '리프레시' }, price: '$85', period: { en: 'per session', ko: '회당' }, features: { en: ['30-min express facial', 'Deep cleanse', 'Hydrating mask', 'SPF finish'], ko: ['30분 익스프레스 페이셜', '딥 클렌징', '보습 마스크', 'SPF 마무리'] } },
      { name: { en: 'Glow', ko: '글로우' }, price: '$130', period: { en: 'per session', ko: '회당' }, featured: true, features: { en: ['60-min luxury facial', 'HydraFacial technology', 'LED therapy', 'Custom serum', 'Take-home sample'], ko: ['60분 럭셔리 페이셜', '하이드라페이셜 기술', 'LED 테라피', '커스텀 세럼', '홈케어 샘플'] } },
      { name: { en: 'Glow Monthly', ko: '글로우 월정액' }, price: '$99', period: { en: '/ month', ko: '/ 월' }, badge: { en: 'SAVE 25%', ko: '25% 절약' }, features: { en: ['1 Glow session / month', 'Skin tracking journal', 'Priority booking', 'Member discounts'], ko: ['월 글로우 세션 1회', '피부 관리 일지', '우선 예약', '회원 할인'] } },
    ],
    products: [
      { name: 'Tatcha The Water Cream', price: '$72', tag: { en: 'Editor\'s Pick', ko: '에디터 추천' }, color: '#c4b5fd' },
      { name: 'La Mer Moisturizing Cream', price: '$95', tag: { en: 'Luxury', ko: '럭셔리' }, color: '#f0c4d4' },
      { name: 'Sunday Riley Good Genes', price: '$55', tag: { en: 'Bestseller', ko: '베스트셀러' }, color: '#bbf7d0' },
    ],
  },
  {
    slug: 'laser',
    accent: '#bbf7d0',
    accentStrong: '#16a34a',
    chip: 'chip-green',
    name:    { en: 'Laser Treatments',           ko: '레이저 시술' },
    short:   { en: 'Laser',                      ko: '레이저' },
    tagline: { en: 'Precision at every wavelength', ko: '모든 파장에서의 정밀함' },
    desc:    { en: 'Medical-grade laser technology for permanent hair removal, skin resurfacing, and rejuvenation. Safe, fast, and effective.', ko: '영구 제모, 피부 재생, 리쥬베네이션을 위한 의료급 레이저 기술. 안전하고 빠르고 효과적입니다.' },
    duration:{ en: '15 – 60 min', ko: '15–60분' },
    from:    { en: 'From $60',    ko: '$60부터' },
    tags:    { en: ['Hair Removal', 'Skin Resurfacing', 'Rejuvenation', 'Pigmentation'], ko: ['제모', '피부 재생', '리쥬베네이션', '색소 침착'] },
    steps: [
      { en: 'Free consultation & patch test', ko: '무료 상담 및 패치 테스트' },
      { en: 'Treatment area preparation', ko: '시술 부위 준비' },
      { en: 'Laser session', ko: '레이저 세션' },
      { en: 'Cooling & soothing aftercare', ko: '쿨링 및 진정 사후 관리' },
      { en: 'SPF protection & follow-up plan', ko: 'SPF 보호 및 후속 계획' },
    ],
    faq: [
      { q: { en: 'How many sessions do I need?', ko: '몇 회나 받아야 하나요?' }, a: { en: 'Most clients need 6–8 sessions for permanent reduction, spaced 4–6 weeks apart.', ko: '대부분의 고객은 4~6주 간격으로 6~8회 세션이 필요합니다.' } },
      { q: { en: 'Is laser hair removal painful?', ko: '레이저 제모가 아픈가요?' }, a: { en: 'Most describe it as a mild snap. We use a cooling device to minimise discomfort.', ko: '대부분 가벼운 튕기는 느낌으로 묘사합니다. 불편함을 최소화하기 위해 쿨링 장치를 사용합니다.' } },
    ],
    packages: [
      { name: { en: 'Single Area', ko: '단일 부위' }, price: '$60', period: { en: 'per session', ko: '회당' }, features: { en: ['1 area per session', 'Consultation included', 'Aftercare guide'], ko: ['회당 1개 부위', '상담 포함', '애프터케어 가이드'] } },
      { name: { en: '6-Session Bundle', ko: '6회 패키지' }, price: '$299', period: { en: 'per area', ko: '부위당' }, featured: true, features: { en: ['6 sessions 1 area', 'Save over 15%', 'Free touch-up', 'Priority scheduling'], ko: ['1개 부위 6회', '15% 이상 절약', '무료 터치업', '우선 예약'] } },
      { name: { en: 'Monthly Unlimited', ko: '월정액 무제한' }, price: '$149', period: { en: '/ month', ko: '/ 월' }, badge: { en: 'BEST VALUE', ko: '최고 가성비' }, features: { en: ['Unlimited sessions', 'All body areas', 'Priority booking', 'Free consultations'], ko: ['무제한 세션', '전신 부위', '우선 예약', '무료 상담'] } },
    ],
    products: [
      { name: 'EltaMD UV Clear SPF 46', price: '$38', tag: { en: 'Post-Laser Must', ko: '레이저 후 필수' }, color: '#bbf7d0' },
      { name: 'Aloe Vera Soothing Gel', price: '$16', tag: { en: 'Aftercare', ko: '사후 관리' }, color: '#bae6fd' },
      { name: 'CeraVe Healing Ointment', price: '$18', tag: { en: 'Bestseller', ko: '베스트셀러' }, color: '#f0c4d4' },
    ],
  },
  {
    slug: 'tattoo',
    accent: '#bae6fd',
    accentStrong: '#0284c7',
    chip: 'chip-blue',
    name:    { en: 'Tattoo Artistry',      ko: '타투 아트' },
    short:   { en: 'Tattoo',               ko: '타투' },
    tagline: { en: 'Art that lasts forever', ko: '영원히 남는 예술' },
    desc:    { en: 'Fine line, botanical, and watercolour works by our resident tattoo artists. Every piece is custom, every client is unique.', ko: '파인 라인, 보태니컬, 수채화 스타일까지. 모든 작품은 커스텀이며, 모든 고객은 특별합니다.' },
    duration:{ en: '1 – 4 hrs', ko: '1–4시간' },
    from:    { en: 'From $150', ko: '$150부터' },
    tags:    { en: ['Fine Line', 'Botanical', 'Watercolour', 'Minimalist', 'Black & Grey'], ko: ['파인 라인', '보태니컬', '수채화', '미니멀', '블랙 & 그레이'] },
    steps: [
      { en: 'Free design consultation', ko: '무료 디자인 상담' },
      { en: 'Custom artwork creation', ko: '커스텀 아트워크 제작' },
      { en: 'Stencil placement approval', ko: '스텐실 위치 승인' },
      { en: 'Tattoo session', ko: '타투 세션' },
      { en: 'Aftercare & healing guidance', ko: '사후 관리 및 치유 안내' },
    ],
    faq: [
      { q: { en: 'How do I book a tattoo consultation?', ko: '타투 상담은 어떻게 예약하나요?' }, a: { en: 'Use our contact form and mention "tattoo consultation". We\'ll match you with the right artist.', ko: '연락처 양식을 사용하여 "타투 상담"을 언급해 주세요. 적합한 아티스트를 연결해 드립니다.' } },
      { q: { en: 'Can you replicate a reference tattoo?', ko: '레퍼런스 타투를 재현할 수 있나요?' }, a: { en: 'We can adapt and reinterpret styles, but all work is original art — never direct copies.', ko: '스타일을 응용하고 재해석할 수 있지만, 모든 작품은 오리지널 아트입니다 — 직접 복사는 하지 않습니다.' } },
    ],
    packages: [
      { name: { en: 'Mini Tattoo', ko: '미니 타투' }, price: '$150', period: { en: 'per piece', ko: '작품당' }, features: { en: ['Up to 2" design', 'Consultation included', 'Aftercare kit'], ko: ['2인치 이하 디자인', '상담 포함', '애프터케어 키트'] } },
      { name: { en: 'Custom Session', ko: '커스텀 세션' }, price: '$200', period: { en: 'per hour', ko: '시간당' }, featured: true, features: { en: ['Custom design', 'Any size & style', 'Artist consultation', 'Touch-up included', 'Aftercare kit'], ko: ['커스텀 디자인', '모든 크기 & 스타일', '아티스트 상담', '터치업 포함', '애프터케어 키트'] } },
      { name: { en: 'Collector Plan', ko: '컬렉터 플랜' }, price: '$350', period: { en: '/ month', ko: '/ 월' }, badge: { en: 'FOR ENTHUSIASTS', ko: '마니아용' }, features: { en: ['4 hrs of studio time', 'Priority artist access', 'Design library access', '15% off products'], ko: ['4시간 스튜디오 시간', '아티스트 우선 접근', '디자인 라이브러리 접근', '제품 15% 할인'] } },
    ],
    products: [
      { name: 'Hustle Butter Deluxe', price: '$24', tag: { en: 'Healing Essential', ko: '치유 필수품' }, color: '#bae6fd' },
      { name: 'Saniderm Tattoo Bandage', price: '$19', tag: { en: 'Aftercare', ko: '사후 관리' }, color: '#bbf7d0' },
      { name: 'Lubriderm Unscented Lotion', price: '$12', tag: { en: 'Moisturiser', ko: '보습제' }, color: '#f0c4d4' },
    ],
  },
  {
    slug: 'pedicure-manicure',
    accent: '#fde68a',
    accentStrong: '#d97706',
    chip: 'chip-pink',
    name:    { en: 'Pedicure & Manicure', ko: '페디큐어 & 매니큐어' },
    short:   { en: 'Pedicure',            ko: '페디큐어' },
    tagline: { en: 'A full ritual for hands and feet', ko: '손과 발을 위한 완전한 의식' },
    desc:    { en: 'A luxurious ritual for hands and feet — exfoliation, massage, colour, and care. Leave softer, smoother, more radiant.', ko: '손발을 위한 럭셔리 리추얼 — 각질 제거, 마사지, 컬러링, 케어. 더 부드럽고 매끄럽고 빛나게.' },
    duration:{ en: '45 – 75 min', ko: '45–75분' },
    from:    { en: 'From $40',    ko: '$40부터' },
    tags:    { en: ['Classic', 'Spa', 'Gel', 'French', 'Paraffin'], ko: ['클래식', '스파', '젤', '프렌치', '파라핀'] },
    steps: [
      { en: 'Soak & softening treatment', ko: '소킹 및 소프닝 트리트먼트' },
      { en: 'Cuticle care & shaping', ko: '큐티클 케어 및 모양 정리' },
      { en: 'Exfoliation & scrub', ko: '각질 제거 및 스크럽' },
      { en: 'Relaxing massage', ko: '릴렉싱 마사지' },
      { en: 'Colour & top coat finish', ko: '컬러링 및 탑 코트 마무리' },
    ],
    faq: [
      { q: { en: 'What is the difference between a classic and spa pedicure?', ko: '클래식과 스파 페디큐어의 차이는 무엇인가요?' }, a: { en: 'The spa version adds a longer massage, exfoliation treatment, and a hydrating paraffin dip.', ko: '스파 버전은 더 긴 마사지, 각질 제거 트리트먼트, 보습 파라핀 딥이 추가됩니다.' } },
    ],
    packages: [
      { name: { en: 'Classic', ko: '클래식' }, price: '$40', period: { en: 'per session', ko: '회당' }, features: { en: ['30 min treatment', 'Standard polish', 'Basic massage', 'Cuticle care'], ko: ['30분 트리트먼트', '일반 폴리시', '기본 마사지', '큐티클 케어'] } },
      { name: { en: 'Spa Ritual', ko: '스파 리추얼' }, price: '$70', period: { en: 'per session', ko: '회당' }, featured: true, features: { en: ['60 min full treatment', 'Gel colour', 'Exfoliation', 'Extended massage', 'Paraffin dip'], ko: ['60분 풀 트리트먼트', '젤 컬러', '각질 제거', '연장 마사지', '파라핀 딥'] } },
      { name: { en: 'Ritual Club', ko: '리추얼 클럽' }, price: '$55', period: { en: '/ month', ko: '/ 월' }, badge: { en: 'SAVE 20%', ko: '20% 절약' }, features: { en: ['1 Spa Ritual / month', 'Priority booking', 'Product discounts'], ko: ['월 스파 리추얼 1회', '우선 예약', '제품 할인'] } },
    ],
    products: [
      { name: 'OPI ProSpa Nail & Cuticle Oil', price: '$20', tag: { en: 'Daily Use', ko: '매일 사용' }, color: '#fde68a' },
      { name: 'Burt\'s Bees Coconut Foot Cream', price: '$14', tag: { en: 'Bestseller', ko: '베스트셀러' }, color: '#bbf7d0' },
      { name: 'Sally Hansen Miracle Gel Top', price: '$12', tag: { en: 'At-Home', ko: '홈케어' }, color: '#bae6fd' },
    ],
  },
  {
    slug: 'eyebrow-lash',
    accent: '#f0c4d4',
    accentStrong: '#e879a0',
    chip: 'chip-pink',
    name:    { en: 'Eyebrow & Lash',             ko: '눈썹 & 속눈썹' },
    short:   { en: 'Brow & Lash',                ko: '눈썹 & 속눈썹' },
    tagline: { en: 'Framing your natural beauty', ko: '자연스러운 아름다움을 완성하다' },
    desc:    { en: 'Threading, tinting, lamination and extensions precisely shaped to your facial features. Define your look effortlessly.', ko: '쓰레딩, 틴팅, 라미네이션, 연장까지 얼굴 형태에 맞게 정밀하게 디자인합니다.' },
    duration:{ en: '30 – 60 min', ko: '30–60분' },
    from:    { en: 'From $35',    ko: '$35부터' },
    tags:    { en: ['Threading', 'Lamination', 'Tinting', 'Extensions', 'Microblading'], ko: ['쓰레딩', '라미네이션', '틴팅', '연장', '마이크로블레이딩'] },
    steps: [
      { en: 'Face shape & feature analysis', ko: '얼굴 형태 및 특징 분석' },
      { en: 'Threading or waxing', ko: '쓰레딩 또는 왁싱' },
      { en: 'Tinting (optional)', ko: '틴팅 (선택)' },
      { en: 'Lamination & setting gel', ko: '라미네이션 및 세팅 젤' },
      { en: 'Final shaping & styling', ko: '최종 모양 정리 및 스타일링' },
    ],
    faq: [
      { q: { en: 'How long does brow lamination last?', ko: '눈썹 라미네이션은 얼마나 지속되나요?' }, a: { en: 'Brow lamination typically lasts 6–8 weeks. Avoid water for 24h post-treatment.', ko: '눈썹 라미네이션은 보통 6~8주 지속됩니다. 시술 후 24시간 동안 물을 피해 주세요.' } },
    ],
    packages: [
      { name: { en: 'Shape & Thread', ko: '쉐이핑 & 쓰레딩' }, price: '$35', period: { en: 'per session', ko: '회당' }, features: { en: ['Threading only', 'Shape mapping', 'Quick tidy'], ko: ['쓰레딩만', '모양 설계', '빠른 정리'] } },
      { name: { en: 'Brow Lamination', ko: '눈썹 라미네이션' }, price: '$75', period: { en: 'per session', ko: '회당' }, featured: true, features: { en: ['Full lamination', 'Tinting', 'Threading', 'Setting gel', 'Aftercare kit'], ko: ['풀 라미네이션', '틴팅', '쓰레딩', '세팅 젤', '애프터케어 키트'] } },
      { name: { en: 'Beauty Monthly', ko: '뷰티 월정액' }, price: '$59', period: { en: '/ month', ko: '/ 월' }, badge: { en: 'SAVE 20%', ko: '20% 절약' }, features: { en: ['1 Lamination / month', 'Free threading touch-ups', 'Priority booking'], ko: ['월 라미네이션 1회', '쓰레딩 무료 터치업', '우선 예약'] } },
    ],
    products: [
      { name: 'Anastasia Beverly Hills Brow Gel', price: '$28', tag: { en: 'Staff Pick', ko: '스태프 추천' }, color: '#f0c4d4' },
      { name: 'Boy Brow by Glossier', price: '$22', tag: { en: 'Cult Favourite', ko: '컬트 제품' }, color: '#c4b5fd' },
      { name: 'NARS Climax Mascara', price: '$32', tag: { en: 'Bestseller', ko: '베스트셀러' }, color: '#bae6fd' },
    ],
  },
  {
    slug: 'waxing',
    accent: '#bbf7d0',
    accentStrong: '#16a34a',
    chip: 'chip-green',
    name:    { en: 'Waxing',                       ko: '왁싱' },
    short:   { en: 'Waxing',                        ko: '왁싱' },
    tagline: { en: 'Smooth. Confident. Radiant.',   ko: '매끄럽고. 자신감 있고. 빛나는.' },
    desc:    { en: 'Smooth, long-lasting results in a calm and private setting. All skin types welcome, all areas covered.', ko: '차분하고 프라이빗한 공간에서 매끄럽고 오래 지속되는 결과를. 모든 피부 타입, 모든 부위 가능.' },
    duration:{ en: '20 – 60 min', ko: '20–60분' },
    from:    { en: 'From $30',    ko: '$30부터' },
    tags:    { en: ['Full Body', 'Brazilian', 'Facial', 'Hard Wax', 'Sensitive Skin'], ko: ['전신', '브라질리안', '페이셜', '하드 왁스', '민감성 피부'] },
    steps: [
      { en: 'Skin consultation & prep', ko: '피부 상담 및 준비' },
      { en: 'Cleanse & prime area', ko: '부위 클렌징 및 프라이밍' },
      { en: 'Wax application & removal', ko: '왁스 도포 및 제거' },
      { en: 'Soothing aftercare lotion', ko: '진정 사후 관리 로션' },
      { en: 'Bump prevention guide', ko: '모낭 방지 가이드' },
    ],
    faq: [
      { q: { en: 'How long should hair be before waxing?', ko: '왁싱 전 털의 길이는 얼마나 되어야 하나요?' }, a: { en: 'At least 1/4 inch (about 2 weeks of growth) for best results.', ko: '최상의 결과를 위해 최소 6mm(약 2주 성장) 이상이어야 합니다.' } },
      { q: { en: 'Is it okay to wax sensitive skin?', ko: '민감성 피부도 왁싱이 가능한가요?' }, a: { en: 'Yes — we use specially formulated hard wax for sensitive areas to minimise irritation.', ko: '네 — 자극을 최소화하기 위해 민감 부위용 특수 제형의 하드 왁스를 사용합니다.' } },
    ],
    packages: [
      { name: { en: 'Single Area', ko: '단일 부위' }, price: '$30', period: { en: 'per session', ko: '회당' }, features: { en: ['1 area', 'Any body part', 'Aftercare lotion'], ko: ['1개 부위', '모든 신체 부위', '애프터케어 로션'] } },
      { name: { en: 'Full Body', ko: '전신' }, price: '$120', period: { en: 'per session', ko: '회당' }, featured: true, features: { en: ['All body areas', 'Hard & soft wax', 'Soothing treatment', 'Bump prevention kit'], ko: ['전신 부위', '하드 & 소프트 왁스', '진정 트리트먼트', '모낭 방지 키트'] } },
      { name: { en: 'Smooth Monthly', ko: '스무스 월정액' }, price: '$89', period: { en: '/ month', ko: '/ 월' }, badge: { en: 'SAVE 25%', ko: '25% 절약' }, features: { en: ['2 sessions / month', 'Any areas', 'Priority booking', 'Product discounts'], ko: ['월 2회 세션', '모든 부위', '우선 예약', '제품 할인'] } },
    ],
    products: [
      { name: 'Tend Skin Solution', price: '$26', tag: { en: 'Ingrown Fix', ko: '내성 모발 해결' }, color: '#bbf7d0' },
      { name: 'PFB Vanish Chromabright', price: '$34', tag: { en: 'Post-Wax', ko: '왁싱 후' }, color: '#f0c4d4' },
      { name: 'Cetaphil Gentle Cleanser', price: '$16', tag: { en: 'Gentle Care', ko: '순한 케어' }, color: '#bae6fd' },
    ],
  },
  {
    slug: 'salon',
    accent: '#c4b5fd',
    accentStrong: '#7c3aed',
    chip: 'chip-purple',
    name:    { en: 'Full Salon',              ko: '풀 살롱' },
    short:   { en: 'Salon',                   ko: '살롱' },
    tagline: { en: 'Hair that moves with you', ko: '나와 함께 움직이는 헤어' },
    desc:    { en: 'Cut, colour, keratin, and blowouts by our senior stylists. Walk in with a vision, leave with a transformation.', ko: '컷, 컬러, 케라틴, 블로우아웃까지 시니어 스타일리스트의 서비스. 비전을 안고 들어와 변신하여 나가세요.' },
    duration:{ en: '45 – 120 min', ko: '45–120분' },
    from:    { en: 'From $65',     ko: '$65부터' },
    tags:    { en: ['Cut', 'Colour', 'Keratin', 'Blowout', 'Balayage'], ko: ['컷', '컬러', '케라틴', '블로우아웃', '발라야주'] },
    steps: [
      { en: 'Consultation & hair analysis', ko: '상담 및 모발 분석' },
      { en: 'Wash & conditioning treatment', ko: '세정 및 컨디셔닝 트리트먼트' },
      { en: 'Colour or chemical service', ko: '컬러 또는 케미컬 서비스' },
      { en: 'Precision cut & shape', ko: '정밀 컷 및 모양' },
      { en: 'Blowout & style finish', ko: '블로우아웃 및 스타일 마무리' },
    ],
    faq: [
      { q: { en: 'How do I know which colour technique suits me?', ko: '어떤 컬러 기술이 나에게 맞는지 어떻게 아나요?' }, a: { en: 'Book a consultation — our stylists assess your skin tone, hair texture, and lifestyle before recommending.', ko: '상담을 예약하세요 — 스타일리스트가 피부 톤, 모발 질감, 라이프스타일을 평가한 후 추천해 드립니다.' } },
      { q: { en: 'How often should I get a haircut?', ko: '헤어컷은 얼마나 자주 받아야 하나요?' }, a: { en: 'Every 6–8 weeks to maintain shape. Longer styles can go 10–12 weeks.', ko: '모양 유지를 위해 6~8주마다. 긴 스타일은 10~12주도 가능합니다.' } },
    ],
    packages: [
      { name: { en: 'Cut & Style', ko: '컷 & 스타일' }, price: '$65', period: { en: 'per session', ko: '회당' }, features: { en: ['Wash & cut', 'Blowout', 'Style finish', 'Consultation'], ko: ['세정 & 컷', '블로우아웃', '스타일 마무리', '상담'] } },
      { name: { en: 'Colour & Cut', ko: '컬러 & 컷' }, price: '$140', period: { en: 'per session', ko: '회당' }, featured: true, features: { en: ['Full colour or balayage', 'Cut & shape', 'Toning', 'Blowout', 'Take-home treatment'], ko: ['풀 컬러 또는 발라야주', '컷 & 모양', '토닝', '블로우아웃', '홈케어 트리트먼트'] } },
      { name: { en: 'Style Club', ko: '스타일 클럽' }, price: '$99', period: { en: '/ month', ko: '/ 월' }, badge: { en: 'SAVE 30%', ko: '30% 절약' }, features: { en: ['1 Colour & Cut / month', 'Free trims', 'Priority booking', 'Product loyalty points'], ko: ['월 컬러 & 컷 1회', '무료 트리밍', '우선 예약', '제품 로열티 포인트'] } },
    ],
    products: [
      { name: 'Olaplex No.3 Hair Perfector', price: '$42', tag: { en: 'Repair', ko: '보수' }, color: '#c4b5fd' },
      { name: 'Redken All Soft Shampoo', price: '$28', tag: { en: 'Hydrating', ko: '보습' }, color: '#f0c4d4' },
      { name: 'Moroccanoil Treatment', price: '$50', tag: { en: 'Staff Pick', ko: '스태프 추천' }, color: '#bbf7d0' },
    ],
  },
]

export const TESTIMONIALS = [
  { initial: 'A', name: 'Amelia R.', service: { en: 'Nail Art', ko: '네일 아트' }, rating: 5, text: { en: 'The attention to detail at Shinhara is unmatched. My nail artist understood exactly what I wanted. Pure magic.', ko: '신하라의 디테일에 대한 집중력은 타의 추종을 불허합니다. 아티스트가 원하는 것을 정확히 이해했어요.' } },
  { initial: 'S', name: 'Sofia K.',  service: { en: 'HydraFacial', ko: '하이드라페이셜' }, rating: 5, text: { en: "I've been to dozens of spas, nothing compares to Sinhara. My skin glowed for two weeks straight.", ko: '수십 군데 스파를 다녀봤지만 신하라와 비교가 안돼요. 2주 내내 피부가 빛났습니다.' } },
  { initial: 'M', name: 'Maya T.',   service: { en: 'Laser', ko: '레이저' }, rating: 5, text: { en: 'Completely transformative. Professional, gentle, and I felt totally at ease the whole time.', ko: '완전히 변화를 가져다 줬어요. 전문적이고 부드러우며 내내 편안했습니다.' } },
]

export const FAQ_GENERAL = [
  { q: { en: 'Do I need to book in advance?', ko: '사전 예약이 필요한가요?' }, a: { en: 'We recommend booking at least 48 hours ahead. Walk-ins are welcome based on availability.', ko: '48시간 전 예약을 권장합니다. 당일 방문도 가능하나 여석에 따라 다를 수 있습니다.' } },
  { q: { en: 'What is your cancellation policy?', ko: '취소 정책은 어떻게 되나요?' }, a: { en: 'We ask for 24 hours notice. Late cancellations may be subject to a 50% service fee.', ko: '24시간 전 취소를 요청드립니다. 늦은 취소 시 서비스 요금의 50%가 부과될 수 있습니다.' } },
  { q: { en: 'Do you offer gift cards?', ko: '기프트 카드가 있나요?' }, a: { en: 'Yes — available in any denomination, valid for all services, no expiry date.', ko: '네 — 금액 제한 없이 구매 가능하며, 모든 서비스에 사용 가능하고 유효기간이 없습니다.' } },
  { q: { en: 'Is parking available?', ko: '주차가 가능한가요?' }, a: { en: 'Free street parking is available on Jasper Ave NW. Parkade access is 1 block west.', ko: '재스퍼 애비뉴 NW에 무료 노상 주차가 가능합니다. 주차장은 1블록 서쪽에 있습니다.' } },
  { q: { en: 'Do you offer services for special occasions?', ko: '특별한 행사에 맞는 서비스가 있나요?' }, a: { en: 'Yes — we offer group bookings and bridal packages. Contact us for custom quotes.', ko: '네 — 단체 예약 및 브라이달 패키지를 제공합니다. 맞춤 견적은 문의해 주세요.' } },
]
